/** 학생 분석 페이지 **/
const Student_AnalysisPage = () => {
    return (
        <>
            <title>Health-PAPS</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />

            <main>분석 페이지</main>
        </>
    );
};

export default Student_AnalysisPage;
