import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { CardBox } from "../../styles/Card";
import { TopBar } from "../../styles/Topbar";
import { Layout } from "../../styles/Layout";
import styled from "styled-components";
import ArrowForwardIosIcon from "@mui/icons-material/ArrowForwardIos";

/** 선생님이 관리하고 있는 반 리스트 페이지 (메인 페이지에서 측정 결과 입력 누르면 여기로 이동) **/
const Teacher_ListPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Health-PAPS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TopBar>
          <h2>학급 목록</h2>
          <Link href="/teacher/create">
            <button>새로운 학급 생성</button>
          </Link>
        </TopBar>
        <CardBox style={{ maxWidth: "60rem", width: "100%" }}>
          <List>
            <h3>1학년 7반</h3>
            <ArrowForwardIosIcon fontSize="small"></ArrowForwardIosIcon>
          </List>
          <List>
            <h3>2학년 1반</h3>
            <ArrowForwardIosIcon fontSize="small"></ArrowForwardIosIcon>
          </List>
          <List>
            <h3>즐거운 3-2반</h3>
            <ArrowForwardIosIcon fontSize="small"></ArrowForwardIosIcon>
          </List>
        </CardBox>
      </Layout>
    </>
  );
};

const List = styled.li`
  display: flex;
  align-items: center;
  justify-content: space-between;
  text-align: left;
  width: 100%;
  /* border: 1px #00000025 solid; */
  padding: 1rem;
  margin-bottom: 1.5rem;
  border-radius: 10px;
  box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;
`;

export default Teacher_ListPage;
