import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Teacher_ListPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Health-PAPS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>반 목록 페이지</main>
    </>
  );
};

export default Teacher_ListPage;
