import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

/** 선생님이 관리하고 있는 반 리스트 페이지 (메인 페이지에서 측정 결과 입력 누르면 여기로 이동) **/
const Teacher_ListPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Health-PAPS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>반 목록 페이지</main>
    </>
  );
};

export default Teacher_ListPage;
