import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { TopBar } from "../../../styles/TopBar";
import { Layout } from "../../../styles/Layout";
import styled from "styled-components";
import { useRouter } from "next/router";
import TextField from "@mui/material/TextField";

/** 학급 페이지 **/
const Teacher_ClassPage: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Health-PAPS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={{ overflow: "scroll" }}>
        <TopBar>
          <h2>{`${router.query.id} 페이지`}</h2>
        </TopBar>
        <Nav>
          <ul>
            <li className="selected">PAPS 기록지</li>
            <li className="">가입 요청</li>
            <li className="">학생 관리</li>
          </ul>
        </Nav>
        <FormContainer>
          <FixedCol>
            <table>
              <th className="num">번호</th>
              <th className="name">이름</th>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
            </table>
          </FixedCol>
          <MovedCol>
            <table>
              <th>윗몸일으키기</th>
              <th>악력</th>
              <th>제자리멀리뛰기</th>
              <th>왕복달리기</th>
              <th>BMI</th>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
                <td>
                  <TextField
                    id="outlined-basic"
                    variant="outlined"
                    size="small"
                  />
                </td>
              </tr>
            </table>
          </MovedCol>
        </FormContainer>
        <Button>저장하기</Button>
        <Button
          style={{
            backgroundColor: "white",
            color: "#66bb6a",
            border: "1px solid #66bb6a",
          }}
        >
          엑셀로 내보내기
        </Button>
      </Layout>
    </>
  );
};

const Nav = styled.nav`
  width: 100%;
  margin-bottom: 2rem;
  ul {
    display: flex;
    justify-content: space-around;
    padding: 0;
    text-align: center;
  }

  li {
    font-size: 0.9rem;
    width: 100%;
    padding: 0.5rem;
  }

  .selected {
    border-bottom: 3px solid #338a3e;
  }
`;

const FormContainer = styled.div`
  display: flex;
  width: 100%;
  max-width: 1000rem;
  overflow: scroll;
  margin-bottom: 2rem;
`;

const FixedCol = styled.div`
  width: 75%;
  position: sticky;
  left: 0;
  background-color: white;
  z-index: 1;

  th {
    font-size: 0.7rem;
  }

  tr {
    input {
      font-size: 0.8rem;
      text-align: center;
    }
  }

  .num {
    width: 30%;
  }

  .name {
    width: 40%;
  }
`;

const MovedCol = styled.div`
  width: 100%;

  table {
    overflow: scroll;
    width: 300%;
  }

  tr {
    input {
      font-size: 0.8rem;
      text-align: center;
    }
  }

  th {
    font-size: 0.7rem;
  }
`;

const Button = styled.button`
  text-align: center;
  border: 0;
  width: 100%;
  font-size: 1rem;
  font-weight: 600;
  background-color: #66bb6a;
  color: white;
  border-radius: 5px;
  max-width: 50rem;
  margin-top: 1rem;
  padding: 1rem;

  &:hover {
    background-color: #338a3e;
    transition-duration: 0.5s;
  }
`;

export default Teacher_ClassPage;
